--- #YAML:1.0
name:               Context-Micro
version:            0.01
abstract:           Micro Context Class
author:
    - ytnobody <ytnobody aaatttt gmail>
license:            Artistic_2_0
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0
requires:
    perl:  5.006
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
